# ARG build_base_image=golang:1.14-alpine3.13
# ARG execute_base_image=alpine:3.10

# FROM ${build_base_image}


# ENV execute_file_name=app

FROM golang:1.17-alpine3.13

COPY ./ /app
WORKDIR /app

RUN go build -o app